include: package:blackfoot_flutter_lint/blackfoot_flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "**/*.g.dart"
    - "integration_test/**"

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  metrics:
    cyclomatic-complexity: 20
    halstead-volume: 150
    lines-of-code: 150
    maintainability-index: 50
    number-of-methods: 10
    number-of-parameters: 5
    maximum-nesting-level: 5
    source-lines-of-code: 100
    technical-debt:
      threshold: 1
      todo-cost: 161
      ignore-cost: 320
      ignore-for-file-cost: 396
      as-dynamic-cost: 322
      deprecated-annotations-cost: 37
      file-nullsafety-migration-cost: 41
      unit-type: "EUR"
    weight-of-class: 0.33
  rules:
    - arguments-ordering: false
    - prefer-static-class: false
    - avoid-late-keyword: false
    - prefer-single-widget-per-file:
        ignore-private-widgets: true

linter:
  rules:
