name: Analyze and test
on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter analyze --no-pub
      - name: Dart Code Metric report
        uses: dart-code-checker/dart-code-metrics-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fatal_warnings: true
          fatal_performance: true
          fatal_style: true
          check_unused_files: true

  # test:
  #   needs: analyze
  #   strategy:
  #     matrix:
  #       device:
  #         - "iPhone 14 Pro"
  #     fail-fast: true
  #   runs-on: [self-hosted, macOS]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"
  #         cache: true
  #     - uses: mikehardy/buildcache-action@v1
  #     - name: "Upgrade Flutter"
  #       if: contains(github.event.pull_request.labels.*.name, 'upgrade')
  #       run: flutter upgrade
  #     - name: "Run integration tests"
  #       run: flutter test integration_test/main_test.dart -d "${{ matrix.device }}" --dart-define=testing_mode=true
