name: test
on:
  pull_request:
    types: [ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter analyze --no-pub

  test:
    needs: analyze
    strategy:
      matrix:
        device:
          - "iPhone 14 Pro"
      fail-fast: true
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - uses: mikehardy/buildcache-action@v1
      - name: "Unlock macmini keychain"
        run: security unlock-keychain -p "${{ secrets.KEY_PASSWORD }}" login.keychain
      - name: "Run integration tests"
        run: flutter test integration_test/main_test.dart -d "${{ matrix.device }}" --dart-define=testing_mode=true
