name: Analyze and test
on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Get dependencies and install DCM
        run: | 
          flutter pub get
          dart pub global activate dart_code_metrics 5.7.4

      - name: Analyze code
        run: |
          flutter analyze --no-pub 
          dart pub global run dart_code_metrics:metrics lib

  # test:
  #   needs: analyze
  #   strategy:
  #     matrix:
  #       device:
  #         - "iPhone 14 Pro"
  #     fail-fast: true
  #   runs-on: [self-hosted, macOS]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"
  #         cache: true
  #     - uses: mikehardy/buildcache-action@v1
  #     - name: "Run integration tests"
  #       run: flutter test integration_test/main_test.dart -d "${{ matrix.device }}" --dart-define=testing_mode=true
